name: fullscreen_mode
description: Immersive fullscreen for Flutter.

author: perlatus <perlatus@fullscreen_mode.email.vczf.io>
homepage: https://github.com/perlatus/flutter_fullscreen_mode

version: 1.0.1

flutter:
  plugin:
    androidPackage: io.vczf.fullscreen_mode
    pluginClass: FullscreenModePlugin

dependencies:
  flutter:
    sdk: flutter
