name: fullscreen_mode
description: Immersive fullscreen for Flutter.

flutter:
  plugin:
    androidPackage: io.vczf.fullscreen_mode
    pluginClass: FullscreenModePlugin

dependencies:
  flutter:
    sdk: flutter
